---
- name: create folder
  file:
   path: /opt/tomcat
   state: directory
   mode: '0755'

- name: i want to extract tar file
  unarchive:
   src: /home/ubuntu/apache-tomcat-7.0.42.tar.gz
   dest: /opt/tomcat/
   extra_opts: [--strip-components=1]
   remote_src: yes