---
- name: deploy my java application on my tomcat7 server(all node side)
  get_url:
    url: https://naresh123456.s3.amazonaws.com/mahaLogin.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    force_basic_auth: yes 